import { FaTwitter, FaFacebookF, FaInstagram, FaGithub } from "react-icons/fa";

export default function Footer() {
  return (
    <footer className="site-footer relative bg-black text-gray-300 pt-[60px] sm:pt-[60px]  sm:px-[80px]">
      {/* gradient bar is generated by .site-footer::before in CSS (see index.css) */}
      <div className="relative z-[0] px-6">
        {/* Top row: logo + social (stack on small screens) */}
        <div className="w-full flex flex-row sm:flex-row sm:items-center justify-between gap-6">
          <img src="/logo.svg" alt="" className="w-[150px] lg:w-auto lg:h-auto"/>

          <div className="flex items-center gap-3 justify-center">
            {/* social icons - circular small buttons */}
            <a
              className="social-btn inline-flex items-center justify-center w-9 h-9 rounded-full bg-slate-800 hover:bg-slate-700 transition"
              href="#"
              aria-label="Twitter"
            >
              <FaTwitter className="text-sm text-white" />
            </a>
            <a
              className="social-btn inline-flex items-center justify-center w-9 h-9 rounded-full bg-slate-800 hover:bg-slate-700 transition"
              href="#"
              aria-label="Facebook"
            >
              <FaFacebookF className="text-sm text-white" />
            </a>
            <a
              className="social-btn inline-flex items-center justify-center w-9 h-9 rounded-full bg-slate-800 hover:bg-slate-700 transition"
              href="#"
              aria-label="Instagram"
            >
              <FaInstagram className="text-sm text-white" />
            </a>
            <a
              className="social-btn inline-flex items-center justify-center w-9 h-9 rounded-full bg-slate-800 hover:bg-slate-700 transition"
              href="#"
              aria-label="GitHub"
            >
              <FaGithub className="text-sm text-white" />
            </a>
          </div>
        </div>

        {/* divider line */}
        <div className="mt-8 border-t border-gray-800"></div>

        {/* copyright */}
        <div className="pt-6 pb-6 lg:pb-[20px] text-[13px] text-gray-400 text-center">
          © Copyright 2025, All Rights Reserved by Image Nation Edutech
        </div>
      </div>
    </footer>
  );
}
