export default function Footer() {
  return (
    <footer className="site-footer relative bg-black text-gray-300 pt-[60px] lg:pt-[60px]  lg:px-[80px]">
      {/* gradient bar is generated by .site-footer::before in CSS (see index.css) */}
      <div className="relative z-[0] px-6">
        {/* Top row: logo + social (stack on small screens) */}
        <div className="w-full flex flex-col lg:flex-row lg:items-center justify-between gap-6">
          <img src="/logo.svg" alt="" className="w-[150px] lg:w-auto lg:h-auto"/>

          <div className="flex flex-col gap-3 justify-center">
            <h1 className="font-semibold poppins">Contact Us</h1>
            <a className="underline-link" href="mailto:imagenationedutech@hotmail.com">imagenationedutech@hotmail.com</a>
            <a className="underline-link" href="https://wa.me/+2349160347969">+234 916 0347 969</a>
          </div>
        </div>

        {/* divider line */}
        <div className="mt-8 border-t border-gray-800"></div>

        {/* copyright */}
        <div className="pt-6 pb-6 lg:pb-[20px] text-[13px] text-gray-400 text-center">
          © Copyright 2025, All Rights Reserved by Image Nation Edutech
        </div>
      </div>
    </footer>
  );
}
